CREATE TABLE ENROLL (
    SID INT NOT NULL,
    CID INT NOT NULL,
    EnrollmentDate DATE NOT NULL,
    PRIMARY KEY (SID, CID),
    FOREIGN KEY (SID) REFERENCES STUDENT(SID),
    FOREIGN KEY (CID) REFERENCES COURSE(CID)
);