-- Tables: Students
-- Technique: ALTER TABLE (dialect: MySQL)

ALTER TABLE Students 
    MODIFY student_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MODIFY birth_date DATE,
    MODIFY email VARCHAR(255) NOT NULL,
    MODIFY phone VARCHAR(50) NOT NULL,
    ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;