-- Tables: SUPPLIER, PART
-- Technique: DDL (dialect: Mysql)
CREATE TABLE SUPPLY (
    SID INT NOT NULL,
    PID INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL CHECK (Price > 0),
    PRIMARY KEY (SID, PID),
    FOREIGN KEY (SID) REFERENCES SUPPLIER(SID),
    FOREIGN KEY (PID) REFERENCES PART(PID)
);