-- Tables: Employees
-- Technique: ALTER TABLE (dialect: Mysql)
ALTER TABLE Employees
    MODIFY COLUMN emp_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MODIFY COLUMN salary DECIMAL(12,2) NOT NULL DEFAULT 0,
    MODIFY COLUMN status ENUM('ACTIVE', 'INACTIVE', 'RESIGNED') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN employment_type ENUM('FULL_TIME', 'PART_TIME', 'INTERN') NOT NULL DEFAULT 'FULL_TIME',
    ADD COLUMN hire_date DATE,
    DROP COLUMN temp_info;