ALTER TABLE DeliveryOrders DROP COLUMN temp_note;

ALTER TABLE DeliveryOrders CHANGE COLUMN created_text created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE DeliveryOrders ADD COLUMN updated_at DATETIME;

ALTER TABLE DeliveryOrders MODIFY COLUMN order_item_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE DeliveryOrders MODIFY COLUMN order_id VARCHAR(50) NOT NULL;

ALTER TABLE DeliveryOrders MODIFY COLUMN customer_phone VARCHAR(20) NOT NULL;

ALTER TABLE DeliveryOrders MODIFY COLUMN address VARCHAR(255) NOT NULL;

ALTER TABLE DeliveryOrders MODIFY COLUMN shipping_method ENUM('STANDARD', 'EXPRESS', 'SAME_DAY') NOT NULL DEFAULT 'STANDARD';

ALTER TABLE DeliveryOrders MODIFY COLUMN shipping_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE DeliveryOrders MODIFY COLUMN cod_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE DeliveryOrders MODIFY COLUMN delivery_status ENUM('PENDING', 'SHIPPING', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';