 -- Tables: LoyaltyPoints
 -- Technique: Alter Table (dialect: Mysql)
ALTER TABLE LoyaltyPoints
    MODIFY record_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MODIFY customer_id INT NOT NULL,
    MODIFY points DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    MODIFY type ENUM('EARN', 'REDEEM', 'ADJUST') NOT NULL DEFAULT 'EARN',
    MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY expired_at DATE NULL,
    ADD COLUMN status ENUM('ACTIVE', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
    DROP COLUMN note_temp;