 -- Tables: Inventory
 -- Technique: DDL (ALTER TABLE) (dialect: Mysql)

 ALTER TABLE Inventory DROP COLUMN temp_col;

 ALTER TABLE Inventory ADD COLUMN note VARCHAR(255);

 ALTER TABLE Inventory MODIFY item_id INT NOT NULL PRIMARY KEY;

 ALTER TABLE Inventory MODIFY quantity INT NOT NULL DEFAULT 0;

 ALTER TABLE Inventory MODIFY unit_price DECIMAL(10,2) NOT NULL DEFAULT 0;

 ALTER TABLE Inventory MODIFY status ENUM('IN_STOCK', 'OUT_OF_STOCK', 'STOPPED') NOT NULL DEFAULT 'IN_STOCK';

 ALTER TABLE Inventory MODIFY last_updated DATETIME DEFAULT CURRENT_TIMESTAMP;