 -- Tables: Students
 -- Technique: ALTER TABLE (dialect: MySQL)

 ALTER TABLE Students MODIFY COLUMN student_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
 ALTER TABLE Students MODIFY COLUMN birth_date DATE;
 ALTER TABLE Students MODIFY COLUMN email VARCHAR(255) NOT NULL;
 ALTER TABLE Students MODIFY COLUMN phone VARCHAR(50) NOT NULL;
 ALTER TABLE Students ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;