 -- Tables: Inventory
 -- Technique: DDL (ALTER TABLE) (dialect: Mysql)

ALTER TABLE Inventory
    MODIFY COLUMN item_id INT NOT NULL PRIMARY KEY,
    MODIFY COLUMN quantity INT NOT NULL DEFAULT 0,
    MODIFY COLUMN unit_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    MODIFY COLUMN status ENUM('IN_STOCK', 'OUT_OF_STOCK', 'STOPPED') NOT NULL DEFAULT 'IN_STOCK',
    MODIFY COLUMN last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN note VARCHAR(255),
    DROP COLUMN temp_col;