 -- Tables: LoyaltyPoints
 -- Technique: Alter Table (dialect: Mysql)
ALTER TABLE LoyaltyPoints
    MODIFY COLUMN record_id INT AUTO_INCREMENT PRIMARY KEY,
    MODIFY COLUMN customer_id INT NOT NULL,
    MODIFY COLUMN points DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN type ENUM('EARN', 'REDEEM', 'ADJUST') NOT NULL DEFAULT 'EARN',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN expired_at DATE NULL,
    ADD COLUMN status ENUM('ACTIVE', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
    DROP COLUMN note_temp;