CREATE TABLE SALEORDER (
    OrderID INT PRIMARY KEY,
    CustID INT NOT NULL,
    TotalAmount DECIMAL(12,2) NOT NULL CHECK (TotalAmount > 0),
    Status ENUM('NEW','PAID','CANCELLED') NOT NULL,
    FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID)
);