ALTER TABLE DeliveryOrders 
    DROP COLUMN temp_note,
    MODIFY COLUMN created_text DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at DATETIME,
    MODIFY order_item_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MODIFY order_id VARCHAR(50) NOT NULL,
    MODIFY customer_phone VARCHAR(20) NOT NULL,
    MODIFY address VARCHAR(255) NOT NULL,
    MODIFY shipping_method ENUM('STANDARD', 'EXPRESS', 'SAME_DAY') NOT NULL DEFAULT 'STANDARD',
    MODIFY shipping_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
    MODIFY cod_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    MODIFY delivery_status ENUM('PENDING', 'SHIPPING', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';