-- Tables: ACTIVITY_LOG
-- Technique: CREATE TABLE (Mysql)

CREATE TABLE ACTIVITY_LOG (
    LogID INT PRIMARY KEY AUTO_INCREMENT,
    Actor VARCHAR(100) NOT NULL,
    Action VARCHAR(100) NOT NULL,
    Detail TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);