-- Tables: Students
-- Technique: ALTER TABLE (dialect: Mysql)
ALTER TABLE Students
MODIFY COLUMN student_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MODIFY COLUMN birth_date DATE,
MODIFY COLUMN email VARCHAR(255) NOT NULL,
MODIFY COLUMN phone VARCHAR(50) NOT NULL,
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;